### ISSUE TITLE
Switch to wa-sqlite

### ISSUE THREAD

**Issue by schickling** [livestorejs/livestore#118]
## Reasons

- Better performance & smaller bundle footprint
- More persistence backends (e.g. SQLite, improved OPFS SAH implementation, ...)
- Better maintained / more modern JS approach
- Bonus: @rhashimoto seems awesome 🤓 

## Tasks

- [x] Custom SQLite WASM build with session extension + [bytecode extension]([-DSQLITE_ENABLE_BYTECODE_VTAB](https://www.sqlite.org/compile.html#enable_bytecode_vtab)) enabled
- [x] Create patch/fork local sync JS build https://github.com/rhashimoto/wa-sqlite/discussions/200#discussioncomment-10258503
- [x] Adjust SQLite <> LiveStore interface

## Related

- [x] #68 
- [x] #67
