### ISSUE TITLE
Meta: Migration improvements

### ISSUE THREAD

**Issue by schickling** [livestorejs/livestore#62]
This is a long-running issue to track all sorts of improvements and other issues related to migrations in LiveStore:

- [x] https://github.com/livestorejs/livestore/issues/1
- [x] https://github.com/livestorejs/livestore/pull/60
- [x] https://github.com/livestorejs/livestore/issues/65

  
## Validation-related

- [ ] Enforce "rules of mutations"
- [ ]  validate table and mutation schemas on boot
    - [ ]  no duplicate definitions
- [ ] Schema compatibility checks 
- [ ] Bookkeeping for schema history
    - [ ]  mutation defs
    - [ ]  table schema defs

## Mutationlog related

- [ ] More tests
- [ ] more efficient persistence of mutation events (e.g. using Protobuf or similar)
- [ ]  Subsumption behaviour
    - [ ]  Can we derive subsumption automatically?
- [ ]  could we see the log as a tree with dependent events which could enable priority-aware rehydration
- [ ]  consider [HLC](https://cse.buffalo.edu/tech-reports/2014-04.pdf) for mutation event id
    - https://github.com/jlongster/crdt-example-app?tab=readme-ov-file
- [ ]  how to deal with atom-derived mutations?
    - are either additive table defs or atom-queries need to provide default values (which makes this case tricky)
    - possibly those tables need to be opt-out from mutation events
    - backfill new column values with default value defs
 - [ ] https://github.com/livestorejs/livestore/issues/69

## Misc

- [ ] Allow combining different migration strategies (e.g. pick different strategies per table)
  - Possibly via an imperative API
- [ ] Allow for way to call boot during re-hydration
- [ ] https://github.com/livestorejs/livestore/issues/63

## Notes / open questions

- [ ] Should we allow for reads during migrations?
- [ ] Consider specific table kinds (ephemeral, tab local, cross-tab local, global)
